---
version: "3.7"

volumes:
  audiobooks:
  podcasts:
  abookshelf:

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: bookshelf
    restart: always
    ports:
      - 13001:80
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - abookshelf:/config
      - abookshelf:/metadata