---
version: "3.9"
services:
  kerberos-agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=agent1
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent1/config:/home/agent/data/config
      - ./agent1/recordings:/home/agent/data/recordings
  kerberos-agent2:
    image: "kerberos/agent:latest"
    ports:
      - "8082:80"
    volumes:
      - ./agent2/config:/home/agent/data/config
      - ./agent2/recordings:/home/agent/data/recordings
  kerberos-agent3:
    image: "kerberos/agent:latest"
    ports:
      - "8083:80"
    volumes:
      - ./agent3/config:/home/agent/data/config
      - ./agent3/recordings:/home/agent/data/recordings